application: programming-nu
version: 1
runtime: go
api_version: go1
handlers:
- url: /
  script: _go_app
- url: /files
  static_dir: static/files
- url: /stylesheets
  static_dir: static/stylesheets
- url: /xml
  static_dir: static/xml
- url: /
  mime_type: text/html
  static_dir: static
